[project]
name = "kqs_retail"
authors = [
    { name = "KQS", email = "pos@kqs.local" }
]
description = "KQS retail extensions: layby, stock APIs, multi-store helpers"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
